# Generated by Django 4.2.4 on 2023-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
