# Generated by Django 4.2.4 on 2023-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertycategories',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertycategories',
            name='category_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='propertytypes',
            name='type_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
