# Generated by Django 4.2.4 on 2023-08-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertycategories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='attribute_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
